# Generated by Django 4.0.4 on 2022-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='phone_number',
            field=models.CharField(default='no phone number', max_length=250),
        ),
    ]
