# Generated by Django 3.2.1 on 2022-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220529_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
